### PR TITLE
Add MSI + Chocolatey

### PR DESCRIPTION
**Pull request by TerribleDev**
Add MSI installer, and add chocolatey installer.

Note: chocolatey packaging does not occur by default as it requires chocolatey to be installed. Wix however does not require anything special.

### CODE REVIEW

**Comment by TerribleDev** [comment]
sorry I missed a file...I just added it

**Comment by TerribleDev** [comment]
The way this works is that it uses the environment variable BUILD_VERSION to version the package/msi if it doesn't exist it just uses 1.0.0

In theory we could have a CI system set the version number or something. Also we could use the same version to patch the AssemblyInfo files as well, but that can be a separate PR

**Review by plmwong — APPROVED** [review]

**Comment by TerribleDev** [comment]
Im assuming you will publish the choco package? with a build server or something?

I guess I could have included a task to publish a choco package, but its just as easy through the cli.

**Comment by plmwong** [comment]
Yep, I'm going to publish the package soon, manually for this one time, and then set up a CI build.

**Pull request merged**
